apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    type: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    type: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    type: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      type: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.8.1-php7.4-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: wordpressdb
            - name: WORDPRESS_DB_USER
              value: wordpressuser
            - name: WORDPRESS_DB_PASSWORD
              value: password123
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          volumeMounts:
            - name: my-volume
              mountPath: /etc/httpd/conf.d/
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
      volumes:
        - name: my-volume
          configMap:
            name: my-apache
